
source 'https://github.com/sunjinshuai/MYSpesc.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios , '9.0'

target 'MainProject' do
    
#    pod 'MYProtocolManager', :git => 'https://github.com/sunjinshuai/MYProtocolManager', :commit => 'af57c12756da069d46a5dfc5d725567c3459ac29'
    pod 'MYITGInterface'
end
